[ew]
  [ew.move]
  _type = "axis2d"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x,left_y"
  keyboard = "arrow_left,arrow_right,arrow_down,arrow_up"

  [ew.select]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "enter"

  [ew.inventory]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "i"

  [ew.menu]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_b"
  keyboard = "escape"

