[ew]
  [ew.move]
  _type = "axis2d"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x,left_y"
  keyboard = "arrow_left,arrow_right,arrow_down,arrow_up"

  [ew.fire]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "x"

  [ew.reload_violet]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "v"

  [ew.reload_cyan]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_z"
  keyboard = "c"

  [ew.select]
  _type = "trigger"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "x"

