[ew]
  [ew.move]
  _type = "axis2d"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "left_x,left_y"
  keyboard = "arrow_left,arrow_right,arrow_down,arrow_up"

  [ew.fire]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_y"
  keyboard = "space"

  [ew.reload]
  _type = "button"
  _device_order = ["gamepad", "keyboard"]
  gamepad = "face_x"
  keyboard = "r"